import { SEO_LANDING_PAGES, type SeoLandingPageConfig, type SeoLandingSlug } from './seoPages';

const germanCopy: Record<string, string> = {
  'Strava activity to video': 'Strava-Aktivität zum Video',
  'Turn a Strava Activity Into a 3D Route Video': 'Verwandeln Sie eine Strava-Aktivität in ein 3D-Routenvideo',
  'Export your Strava GPX, replay the real route in 3D, and download a polished video with stats and elevation.': 'Exportieren Sie Ihr Strava-GPX, spielen Sie die tatsächliche Route in 3D ab und laden Sie ein ausgefeiltes Video mit Statistiken und Höhenmetern herunter.',
  'Built for real activity data, not a hand-drawn travel line.': 'Gebaut für echte Aktivitätsdaten, nicht für eine handgezeichnete Reiselinie.',
  'From Strava activity to MP4': 'Von der Strava-Aktivität zu MP4',
  'You keep control of the original file. TrailReplay processes the GPX locally in your browser.': 'Sie behalten die Kontrolle über die Originaldatei. TrailReplay verarbeitet die GPX-Datei lokal in Ihrem Browser.',
  'Export the activity': 'Aktivität exportieren',
  'Open your activity on Strava.com, choose Export GPX, and save the file.': 'Öffnen Sie Ihre Aktivität auf Strava.com, wählen Sie „GPX exportieren“ und speichern Sie die Datei.',
  'Drop in the GPX': 'GPX-Datei ablegen',
  'Import it into TrailReplay. Distance, elevation, timestamps, and route geometry are read automatically.': 'Importieren Sie sie in TrailReplay. Distanz, Höhenmeter, Zeitstempel und Streckenverlauf werden automatisch eingelesen.',
  'Shape the replay': 'Wiedergabe gestalten',
  'Choose the map, camera, trail style, statistics, speed, annotations, and export frame.': 'Wählen Sie Karte, Kamera, Streckenstil, Statistiken, Geschwindigkeit, Anmerkungen und Exportformat.',
  'Download the video': 'Video herunterladen',
  'Record an MP4 or WebM ready for editing, YouTube, Instagram, or your ride recap.': 'Nehmen Sie ein MP4 oder WebM auf – bereit für Schnitt, YouTube, Instagram oder Ihren Tourenrückblick.',
  'A replay that still feels like your activity': 'Eine Wiedergabe, die sich wie Ihre Aktivität anfühlt',
  'Recorded route': 'Aufgezeichnete Strecke',
  'Animate the GPX line from the activity you actually completed.': 'Animieren Sie die GPX-Linie der Aktivität, die Sie tatsächlich absolviert haben.',
  'Real statistics': 'Echte Statistiken',
  'Show distance, elevation, pace, speed, and progress where the file supports them.': 'Zeigen Sie Distanz, Höhenmeter, Tempo, Geschwindigkeit und Fortschritt, sofern die Datei diese Daten enthält.',
  'Terrain-aware 3D': '3D mit Geländebezug',
  'Use terrain, camera movement, and elevation to give the route geographical context.': 'Nutzen Sie Gelände, Kamerabewegung und Höhenmeter, um die Strecke geografisch einzuordnen.',
  'How to export a GPX from Strava': 'So exportieren Sie eine GPX-Datei aus Strava',
  'On the Strava website, open one of your own activities, select the three-dot action menu, and choose Export GPX. Strava may limit GPX export for activities that do not belong to you.': 'Öffnen Sie auf der Strava-Website eine eigene Aktivität, wählen Sie das Drei-Punkte-Menü und anschließend „GPX exportieren“. Für Aktivitäten anderer Personen kann Strava den GPX-Export einschränken.',
  'A timestamped activity file produces the most faithful replay. If timestamps are unavailable, TrailReplay can still visualize the route and create an animation using the playback settings you choose.': 'Eine Aktivitätsdatei mit Zeitstempeln liefert die genaueste Wiedergabe. Ohne Zeitstempel kann TrailReplay die Strecke dennoch visualisieren und mit Ihren Wiedergabeeinstellungen animieren.',
  'Does TrailReplay connect to my Strava account?': 'Verbindet sich TrailReplay mit meinem Strava-Konto?',
  'No. Download the GPX from Strava and import it yourself; no Strava login or account connection is required.': 'Nein. Laden Sie die GPX-Datei von Strava herunter und importieren Sie sie selbst. Ein Strava-Login oder eine Kontoverbindung ist nicht erforderlich.',
  'Can I use a Strava route instead of an activity?': 'Kann ich statt einer Aktivität eine Strava-Route verwenden?',
  'Yes, if you can export it as GPX. Activity files usually contain richer timing data.': 'Ja, sofern Sie sie als GPX exportieren können. Aktivitätsdateien enthalten meist detailliertere Zeitdaten.',
  'Is my Strava GPX uploaded?': 'Wird meine Strava-GPX-Datei hochgeladen?',
  'The route is parsed locally in your browser by default and is not uploaded to TrailReplay servers.': 'Die Strecke wird standardmäßig lokal in Ihrem Browser verarbeitet und nicht auf TrailReplay-Server hochgeladen.',
  'Garmin activity to video': 'Garmin-Aktivität zum Video',
  'Turn a Garmin Activity Into a 3D Route Video': 'Verwandeln Sie eine Garmin-Aktivität in ein 3D-Routenvideo',
  'Export GPX from Garmin Connect and create an animated route replay with terrain, elevation, statistics, photos, and video export.': 'Exportieren Sie eine GPX-Datei aus Garmin Connect und erstellen Sie eine animierte Streckenwiedergabe mit Gelände, Höhenmetern, Statistiken, Fotos und Videoexport.',
  'Works from a standard GPX export. No Garmin account connection needed.': 'Funktioniert mit einem Standard-GPX-Export. Keine Garmin-Kontoverbindung nötig.',
  'Create a Garmin route replay': 'Garmin-Streckenwiedergabe erstellen',
  'Start with the original activity export to preserve as much route and timing detail as possible.': 'Beginnen Sie mit dem originalen Aktivitätsexport, um möglichst viele Strecken- und Zeitdetails zu erhalten.',
  'Open Garmin Connect': 'Garmin Connect öffnen',
  'Open the completed activity on the Garmin Connect website.': 'Öffnen Sie die abgeschlossene Aktivität auf der Garmin-Connect-Website.',
  'Export the GPX': 'GPX-Datei exportieren',
  'Use the activity settings menu and select Export to GPX.': 'Öffnen Sie das Aktivitätsmenü und wählen Sie „Als GPX exportieren“.',
  'Customize the route': 'Strecke anpassen',
  'Import the file, choose the map and camera, and add stats, elevation, photos, or text.': 'Importieren Sie die Datei, wählen Sie Karte und Kamera und ergänzen Sie Statistiken, Höhenmeter, Fotos oder Text.',
  'Export your replay': 'Wiedergabe exportieren',
  'Record a landscape, square, or vertical route video for your preferred channel.': 'Nehmen Sie ein Streckenvideo im Querformat, Quadrat oder Hochformat für Ihren bevorzugten Kanal auf.',
  'Use the detail your Garmin recorded': 'Nutzen Sie die Details, die Ihr Garmin aufgezeichnet hat',
  'Activity-first': 'Aus der Aktivität heraus',
  'Build the story around the route and timestamps captured by your device.': 'Bauen Sie die Geschichte aus der Strecke und den Zeitstempeln auf, die Ihr Gerät aufgezeichnet hat.',
  'Sport statistics': 'Sportstatistiken',
  'Display useful motion and route metrics in the exported video.': 'Zeigen Sie im exportierten Video aussagekräftige Bewegungs- und Streckenwerte an.',
  'Flexible output': 'Flexibler Export',
  'Choose MP4 or WebM with export settings for different aspect ratios and quality levels.': 'Wählen Sie MP4 oder WebM mit Exporteinstellungen für verschiedene Seitenverhältnisse und Qualitätsstufen.',
  'Exporting from Garmin Connect': 'Export aus Garmin Connect',
  'Use Garmin Connect in a desktop browser, open the activity detail, select the gear icon, and choose Export to GPX. The exact menu wording can vary as Garmin updates Connect.': 'Nutzen Sie Garmin Connect in einem Desktop-Browser: Öffnen Sie die Aktivitätsdetails, wählen Sie das Zahnradsymbol und dann „Als GPX exportieren“. Die genaue Menübezeichnung kann sich mit Garmin Connect ändern.',
  'GPX is ideal for route geometry and broadly compatible timestamps. If you only have a FIT file, export or convert it to GPX before importing it into TrailReplay.': 'GPX eignet sich ideal für Streckenverläufe und kompatible Zeitstempel. Wenn Sie nur eine FIT-Datei haben, exportieren oder konvertieren Sie sie vor dem Import in TrailReplay zu GPX.',
  'Does this work with Garmin watches and bike computers?': 'Funktioniert das mit Garmin-Uhren und Fahrradcomputern?',
  'Yes. If the recorded activity appears in Garmin Connect and can be exported as GPX, TrailReplay can import it.': 'Ja. Wenn die aufgezeichnete Aktivität in Garmin Connect erscheint und als GPX exportiert werden kann, kann TrailReplay sie importieren.',
  'Do I need to install software?': 'Muss ich Software installieren?',
  'No. TrailReplay runs in a modern desktop browser.': 'Nein. TrailReplay läuft in einem modernen Desktop-Browser.',
  'Can I add photos to a Garmin route replay?': 'Kann ich Fotos zu einer Garmin-Streckenwiedergabe hinzufügen?',
  'Yes. Photos can be positioned using GPS or timestamps when metadata is available, or placed manually.': 'Ja. Fotos können bei verfügbaren Metadaten über GPS oder Zeitstempel positioniert oder manuell platziert werden.',
  'Free GPX animation maker': 'Kostenloser GPX-Animationseditor',
  'Animate a GPX File on a 3D Map': 'Eine GPX-Datei auf einer 3D-Karte animieren',
  'Turn a recorded GPS track into a cinematic route animation with terrain, live statistics, elevation, photos, and downloadable video.': 'Verwandeln Sie einen aufgezeichneten GPS-Track in eine filmische Streckenanimation mit Gelände, Live-Statistiken, Höhenmetern, Fotos und herunterladbarem Video.',
  'Free, open source, and processed in your browser.': 'Kostenlos, Open Source und direkt in Ihrem Browser verarbeitet.',
  'Make a GPX animation in minutes': 'Eine GPX-Animation in wenigen Minuten erstellen',
  'No timeline editor is required. Import a route, compose the view, preview it, and record.': 'Kein Timeline-Editor nötig: Importieren Sie eine Strecke, gestalten Sie die Ansicht, sehen Sie sie in der Vorschau an und zeichnen Sie auf.',
  'Import GPX or KML': 'GPX oder KML importieren',
  'Drop one route or combine multiple tracks into a longer journey.': 'Legen Sie eine Strecke ab oder kombinieren Sie mehrere Tracks zu einer längeren Tour.',
  'Choose the map': 'Karte auswählen',
  'Select imagery, terrain, trail color, camera behavior, and the section of the route to show.': 'Wählen Sie Bildmaterial, Gelände, Streckenfarbe, Kameraverhalten und den anzuzeigenden Streckenabschnitt.',
  'Add the story': 'Geschichte ergänzen',
  'Include elevation, statistics, pictures, labels, annotations, or a comparison track.': 'Ergänzen Sie Höhenmeter, Statistiken, Bilder, Beschriftungen, Anmerkungen oder einen Vergleichstrack.',
  'Record the animation': 'Animation aufzeichnen',
  'Export the replay as a video or capture a social-ready still image.': 'Exportieren Sie die Wiedergabe als Video oder erstellen Sie ein Standbild für Social Media.',
  'More than a moving line': 'Mehr als eine bewegte Linie',
  'Map and terrain': 'Karte und Gelände',
  'Put the route in its real landscape with configurable basemaps and 3D terrain.': 'Setzen Sie die Strecke mit konfigurierbaren Basiskarten und 3D-Gelände in ihre reale Landschaft.',
  'Story controls': 'Steuerung für Ihre Story',
  'Control pace, camera, crop, visual style, pictures, and annotations.': 'Steuern Sie Tempo, Kamera, Ausschnitt, visuellen Stil, Bilder und Anmerkungen.',
  'Files you can use': 'Dateien zur Weiterverwendung',
  'Download the result for a video editor or publish it directly.': 'Laden Sie das Ergebnis für einen Videoeditor herunter oder veröffentlichen Sie es direkt.',
  'What makes a good GPX animation?': 'Was macht eine gute GPX-Animation aus?',
  'A clean track, useful timestamps, and a deliberate camera angle matter more than excessive effects. Start with the whole route, then choose a playback speed that keeps the geography readable.': 'Ein sauberer Track, hilfreiche Zeitstempel und ein bewusster Kamerawinkel sind wichtiger als übertriebene Effekte. Beginnen Sie mit der gesamten Strecke und wählen Sie dann eine Wiedergabegeschwindigkeit, bei der die Geografie verständlich bleibt.',
  'For a vertical social post, preview the 9:16 crop before recording. For YouTube or a longer film, landscape output leaves more space for the map and statistics.': 'Sehen Sie sich für einen vertikalen Social-Media-Beitrag den 9:16-Ausschnitt vor der Aufnahme an. Für YouTube oder einen längeren Film bietet das Querformat mehr Platz für Karte und Statistiken.',
  'What is a GPX animation?': 'Was ist eine GPX-Animation?',
  'It is a timed visual replay of GPS coordinates on a map, usually exported as video for sharing or editing.': 'Sie ist eine zeitgesteuerte visuelle Wiedergabe von GPS-Koordinaten auf einer Karte, die meist als Video zum Teilen oder Bearbeiten exportiert wird.',
  'Can I animate more than one GPX?': 'Kann ich mehr als eine GPX-Datei animieren?',
  'Yes. TrailReplay supports multiple tracks, journeys, and separate comparison tracks.': 'Ja. TrailReplay unterstützt mehrere Tracks, Touren und separate Vergleichstracks.',
  'Can TrailReplay export MP4?': 'Kann TrailReplay MP4 exportieren?',
  'Yes, when your browser supports the required encoding path. WebM is available as a fallback.': 'Ja, wenn Ihr Browser den erforderlichen Kodierungspfad unterstützt. WebM steht als Alternative bereit.',
  'Cycling route animation': 'Animation einer Fahrradroute',
  'Create an Animated Cycling Route Video': 'Ein animiertes Fahrradroutenvideo erstellen',
  'Transform a road, gravel, MTB, or bikepacking GPX into a 3D video with speed, elevation, distance, photos, and route progress.': 'Verwandeln Sie eine Rennrad-, Gravel-, MTB- oder Bikepacking-GPX-Datei in ein 3D-Video mit Geschwindigkeit, Höhenmetern, Distanz, Fotos und Streckenfortschritt.',
  'One ride, a multi-day journey, or a head-to-head comparison.': 'Eine Fahrt, eine mehrtägige Tour oder ein direkter Vergleich.',
  'Tell the full story of the ride': 'Die ganze Geschichte der Fahrt erzählen',
  'Use a route from your bike computer or activity platform, then make the geography easy to follow.': 'Nutzen Sie eine Strecke von Ihrem Fahrradcomputer oder Ihrer Aktivitätsplattform und machen Sie die Geografie leicht nachvollziehbar.',
  'Get the ride GPX': 'GPX-Datei der Fahrt besorgen',
  'Export from Garmin, Strava, Komoot, Ride with GPS, or another service.': 'Exportieren Sie von Garmin, Strava, Komoot, Ride with GPS oder einem anderen Dienst.',
  'Frame the terrain': 'Gelände in Szene setzen',
  'Choose a camera and map that make climbs, descents, and switchbacks legible.': 'Wählen Sie eine Kamera und Karte, die Anstiege, Abfahrten und Serpentinen gut lesbar machen.',
  'Add ride context': 'Kontext zur Fahrt ergänzen',
  'Show distance, speed, elevation, progress, pictures, and day-by-day journey segments.': 'Zeigen Sie Distanz, Geschwindigkeit, Höhenmeter, Fortschritt, Bilder und Tagesabschnitte der Tour.',
  'Export for your channel': 'Für Ihren Kanal exportieren',
  'Record landscape for YouTube or vertical and square variants for social posts.': 'Nehmen Sie im Querformat für YouTube oder in Hochformat- und Quadratvarianten für Social Media auf.',
  'Designed for the shape of a ride': 'Für die Besonderheiten einer Fahrt entwickelt',
  'Road to bikepacking': 'Vom Rennrad bis Bikepacking',
  'Use one recorded ride or assemble multiple GPX files into a continuous journey.': 'Nutzen Sie eine aufgezeichnete Fahrt oder verbinden Sie mehrere GPX-Dateien zu einer durchgehenden Tour.',
  'Climbs in context': 'Anstiege im Kontext',
  'Pair 3D terrain and elevation data to show why a route felt hard.': 'Kombinieren Sie 3D-Gelände und Höhendaten, um zu zeigen, warum sich eine Strecke anspruchsvoll anfühlte.',
  'Ride progression': 'Fortschritt der Fahrt',
  'Use timing data and playback controls to communicate the rhythm of the activity.': 'Nutzen Sie Zeitdaten und Wiedergabesteuerung, um den Rhythmus der Aktivität zu vermitteln.',
  'Cycling videos that explain the route': 'Fahrradvideos, die die Strecke erklären',
  'A route animation is useful before the ride as a course overview and after it as part of a recap. It can bridge footage gaps while showing viewers where the next climb, town, or stage fits.': 'Eine Streckenanimation hilft vor der Fahrt als Kursüberblick und danach als Teil eines Rückblicks. Sie überbrückt Lücken im Filmmaterial und zeigt, wo der nächste Anstieg, Ort oder die nächste Etappe liegt.',
  'For long-distance trips, combine daily GPX files into a journey and use annotations or photos to mark stops. For races, add a comparison track to explain two lines or attempts.': 'Kombinieren Sie für Langstreckentouren tägliche GPX-Dateien zu einer Tour und markieren Sie Stopps mit Anmerkungen oder Fotos. Für Rennen können Sie einen Vergleichstrack hinzufügen, um zwei Linien oder Versuche zu erklären.',
  'Can I animate a multi-day bikepacking route?': 'Kann ich eine mehrtägige Bikepacking-Route animieren?',
  'Yes. Import multiple GPX files and organize them as journey segments.': 'Ja. Importieren Sie mehrere GPX-Dateien und organisieren Sie sie als Tourabschnitte.',
  'Can it show speed and elevation?': 'Kann es Geschwindigkeit und Höhenmeter anzeigen?',
  'TrailReplay can display statistics supported by the imported data and calculated route profile.': 'TrailReplay kann Statistiken anzeigen, die von den importierten Daten und dem berechneten Streckenprofil unterstützt werden.',
  'Which cycling platforms work?': 'Welche Fahrradplattformen werden unterstützt?',
  'Any platform that lets you export a standard GPX or KML route can feed TrailReplay.': 'Jede Plattform, aus der Sie eine Standard-GPX- oder KML-Strecke exportieren können, funktioniert mit TrailReplay.',
  'Running route animation': 'Animation einer Laufstrecke',
  'Create an Animated Running Route Video': 'Ein animiertes Laufstreckenvideo erstellen',
  'Turn a road race, marathon, trail run, or ultra GPX into a 3D replay with pace, elevation, distance, photos, and progress.': 'Verwandeln Sie eine GPX-Datei von Straßenrennen, Marathon, Trailrun oder Ultra in eine 3D-Wiedergabe mit Tempo, Höhenmetern, Distanz, Fotos und Fortschritt.',
  'Make the course and the effort understandable at a glance.': 'Machen Sie Strecke und Anstrengung auf einen Blick verständlich.',
  'From finish line to route replay': 'Von der Ziellinie zur Streckenwiedergabe',
  'Start with the activity GPX from your watch or training platform and build the story around the course.': 'Beginnen Sie mit der Aktivitäts-GPX Ihrer Uhr oder Trainingsplattform und erzählen Sie die Geschichte entlang der Strecke.',
  'Export your run': 'Lauf exportieren',
  'Download GPX from Strava, Garmin Connect, Coros, Suunto, or another activity service.': 'Laden Sie GPX-Dateien von Strava, Garmin Connect, Coros, Suunto oder einem anderen Aktivitätsdienst herunter.',
  'Import the course': 'Strecke importieren',
  'TrailReplay reads the route, distance, timing, and available elevation information.': 'TrailReplay liest Strecke, Distanz, Zeitinformationen und verfügbare Höhendaten ein.',
  'Show the effort': 'Anstrengung zeigen',
  'Choose pace, elevation, progress, camera, map style, photos, and annotations.': 'Wählen Sie Tempo, Höhenmeter, Fortschritt, Kamera, Kartenstil, Fotos und Anmerkungen.',
  'Share the result': 'Ergebnis teilen',
  'Export a route video for your race recap, club, coach, film, or social post.': 'Exportieren Sie ein Streckenvideo für Ihren Rennrückblick, Verein, Trainer, Film oder Social-Media-Beitrag.',
  'Made for races, trails, and long days out': 'Für Rennen, Trails und lange Tage draußen gemacht',
  'Any running route': 'Jede Laufstrecke',
  'Use a city 5K, marathon course, mountain trail, or ultra-distance track.': 'Nutzen Sie einen 5-km-Lauf in der Stadt, eine Marathonstrecke, einen Bergtrail oder einen Ultradistanz-Track.',
  'Pace and elevation': 'Tempo und Höhenmeter',
  'Give viewers context for the effort and the shape of the course.': 'Geben Sie Zuschauenden Kontext für die Anstrengung und den Verlauf der Strecke.',
  'Photos on the route': 'Fotos entlang der Strecke',
  'Place race and trail photos by GPS, timestamp, or manual position.': 'Platzieren Sie Renn- und Trailfotos per GPS, Zeitstempel oder manuell.',
  'Make a race recap easier to follow': 'Einen Rennrückblick leichter nachvollziehbar machen',
  'A map replay gives structure to race footage and photographs. Use it as an opening course overview, between aid stations, or as a complete visual summary when you did not record video during the run.': 'Eine Kartenwiedergabe gibt Rennaufnahmen und Fotos Struktur. Nutzen Sie sie als Streckenüberblick zu Beginn, zwischen Verpflegungsstationen oder als vollständige Zusammenfassung, wenn Sie beim Lauf kein Video aufgenommen haben.',
  'Trail and ultra routes benefit from a lower camera angle and visible elevation. Road races usually read better with a cleaner overhead view and a crop that keeps the full course visible.': 'Trail- und Ultra-Strecken profitieren von einem niedrigeren Kamerawinkel und sichtbaren Höhenmetern. Straßenrennen sind mit einer klaren Draufsicht und einem Ausschnitt, der die gesamte Strecke zeigt, meist besser lesbar.',
  'Can I make a marathon route animation?': 'Kann ich eine Marathonstrecken-Animation erstellen?',
  'Yes. Import the race activity GPX, customize the replay, and export it as video.': 'Ja. Importieren Sie die Aktivitäts-GPX des Rennens, passen Sie die Wiedergabe an und exportieren Sie sie als Video.',
  'Does it work for trail running and ultras?': 'Funktioniert es für Trailrunning und Ultras?',
  'Yes. 3D terrain, elevation, journey segments, and photos are especially useful for longer trail events.': 'Ja. 3D-Gelände, Höhenmeter, Tourabschnitte und Fotos sind besonders nützlich für längere Trail-Events.',
  'Can I create a vertical running video?': 'Kann ich ein vertikales Laufvideo erstellen?',
  'Yes. Preview and record a 9:16 crop for Reels, Shorts, and TikTok.': 'Ja. Zeigen Sie eine Vorschau an und zeichnen Sie einen 9:16-Ausschnitt für Reels, Shorts und TikTok auf.',
};

function localize(value: unknown): unknown {
  if (typeof value === 'string') return germanCopy[value] ?? value;
  if (Array.isArray(value)) return value.map(localize);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, localize(item)]));
  }
  return value;
}

export const SEO_LANDING_PAGES_DE = localize(SEO_LANDING_PAGES) as Record<SeoLandingSlug, SeoLandingPageConfig>;
